variables:
  APP_NAME: starter-pack
  OTREE_AUTH_LEVEL: "STUDY"
  NAMESPACE: delegating-to-ai-2-psychological-mechanisms
  DEPLOYMENT_VARS: "OTREE_REST_KEY, OTREE_PRODUCTION, OTREE_AUTH_LEVEL, OTREE_ADMIN_PASSWORD, DATABASE_URL, BACKEND_URL, MODEL_CONFIG_NAME, API_APP_USER, API_APP_PASSWORD"

include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "3.0.2"
    file: "otree-app.yml"
